(function(){
    window.IBQuestions = [
        "If you could have a super power, what would it be?",
        "If your home caught on fire and you were able to save one material possession, what would it be?",
        "What happened today that you're most grateful for?",
        "For what in your life do you feel most grateful?",
        "What's your life story in one minute or less?",
        "What did you get detention for when you were in school?",
        "What sport or activity did you do in school?",
        "What do you spend most of your money on?",
        "What three emoji's describe you best?",
        "What's your favorite dish to cook?",
        "What's the most traumatic movie or book you saw/read as a child?",
        "Describe your family in a nutshell.",
        "What would your last meal be?",
        "What would constitute a “perfect” day for you?",
        "What is your favorite childhood book?",
        "If you had a theme song what would it be?",
        "What unusual skills do you have?",
        "Who is your dream dinner guest?",
        "What is the best advice you ever had?",
        "What celebrities did you have a crush on as a kid?",
        "What's something your grandparents taught you?",
        "What was your best Halloween costume ever?", 
        "What is the worst fad you participated in?",
        "Do you have any tattoos? What is the story behind them?",
        "What is your greatest strength?",
        "What advice would you give to yourself at 13 years old?",
        "What is your go-to karaoke song? Extra points for singing part of it.",
        "Who are you dying to see in concert?",
        "What countries have you traveled to? Tell a story from one of them.",
        "What is one item from your bucket list?",
        "What is a life goal you have?",
        "What's your favorite holiday?",
        "What show are you binge watching now?",
        "What is one of the most spontaneous things you've ever done?",
        "How did your parents meet?",
        "What did you want to be when you grew up?",
        "What's a fact about you that surprises people?",
        "What are you irrationally afraid of?",
        "What was the last movie you went to? What did you think?",
        "What book did you last read? What did you think?",
        "Do you like or dislike surprises? Why or why not?",
        "What was your closest near-death experience?
        "What book or TV show changed your life?",
        "Is there something that you've dreamt of doing for a long time? Why haven't you done it?",
        "What was your first job?",
        "What was the best thing that happened to you this past week?",
        "Name a gift you will never forget.",
        "What's the weirdest thing you've ever eaten?"
    ];
})();
