(function(){
    window.IBQuestions = [
        "Given the choice of anyone in the world, whom would you want as a dinner guest?",
        "Would you like to be famous? In what way?",
        "What would constitute a \"perfect\" day for you?",
        "When did you last sing to yourself? To someone else?",
        "If you were able to live to the age of 90 and retain either the mind or body of a 30-year-old for the last 60 years of your life, which would you want?",
        "Before making a telephone call, do you ever rehearse what you are going to say? Why?",
        "What item under $100 has had the biggest positive impact on your life?",
        "Find three things everybody playing has in common.",
        "For what in your life do you feel most grateful?",
        "If you could change anything about the way you were raised, what would it be?",
        "What book or TV show changed your life?",
        "If you could wake up tomorrow having gained any one quality or ability, what would it be?",
        "If a crystal ball could tell you the truth about yourself, your life, the future or anything else, what would you want to know?",
        "Is there something that you've dreamt of doing for a long time? Why haven't you done it?",
        "What is the greatest accomplishment of your life?",
        "What do you value most in a friendship?",
        "What is your most treasured memory?",
        "If you knew that in one year you would die suddenly, would you change anything about the way you are now living? Why?",
        "What does friendship mean to you?",
        "What roles do love and affection play in your life?",
        "What was your first job?",
        "What is your favorite childhood memory?",
        "Complete this sentence \"I wish I had someone with whom I could share...\"",
        "If you could talk about one thing with someone that was just as passionate about the topic as you are, what would that one thing be?",
        "Do you have a pet? If not, what sort of pet would you like?",
        "What was the best thing that happened to you this past week?",
        "When did you last laugh out loud by yourself?",
        "Name a gift you will never forget.",
        "What, if anything, is too serious to be joked about?",
        "What's the weirdest thing you've ever eaten?"
    ];
})();
