(function(){
    window.IBQuestions = [
        "Given the choice of anyone in the world, whom would you want as a dinner guest?",
        "Would you like to be famous? In what way?",
        "What would constitute a \"perfect\" day for you?",
        "When did you last sing to yourself? To someone else?",
        "If you were able to live to the age of 90 and retain either the mind or body of a 30-year-old for the last 60 years of your life, which would you want?",
        "Before making a telephone call, do you ever rehearse what you are going to say? Why?",
        "Do you have a secret hunch about how you will die?",
        "Find three things everybody playing has in common.",
        "For what in your life do you feel most grateful?",
        "If you could change anything about the way you were raised, what would it be?",
        "What book or TV show changed your life?",
        "If you could wake up tomorrow having gained any one quality or ability, what would it be?",
        "If a crystal ball could tell you the truth about yourself, your life, the future or anything else, what would you want to know?",
        "Is there something that you've dreamt of doing for a long time? Why haven't you done it?",
        "What is the greatest accomplishment of your life?",
        "What do you value most in a friendship?",
        "What is your most treasured memory?",
        "What is your most terrible memory?",
        "If you knew that in one year you would die suddenly, would you change anything about the way you are now living? Why?",
        "What does friendship mean to you?",
        "What roles do love and affection play in your life?",
        "What was your first job?",
        "How close and warm is your family? Do you feel your childhood was happier than most other people?",
        "How do you feel about your relationship with your mother?",
        "Make three true \"we\" statements each. For instance, \"we are both in this room feeling...\"",
        "Complete this sentence \"I wish I had someone with whom I could share...\"",
        "If you could talk about one thing with someone that was just as passionate about the topic as you are, what would that one thing be?",
        "Do you have a pet? If not, what sort of pet would you like?",
        "What was the best thing that happened to you this past week?",
        "When did you last cry in front of another person? By yourself?",
        "Name a gift you will never forget.",
        "What, if anything, is too serious to be joked about?",
        "If you were to die this evening with no opportunity to,communicate with anyone, what would you most regret not having told someone? Why haven't you told them yet?",
        "Your house, containing everything you own, catches fire. After saving your loved ones and pets, you have time to safely make a final dash to save any one item. What would it be? Why?",
        "Of all the people in your family, whose death would you find most disturbing? Why?",
        "What's the weirdest thing you've ever eaten?"
    ];
})();
